apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - helm.yaml
  - httproute.yaml

configMapGenerator:
  - name: opentelemetry-demo-helm-values
    files:
      - base-values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml