# opentelemetry-demo helm values (base)

default:
  # Override OTEL collector environement variable in all components
  envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: otel-collector.otel
  # schedulingRules:
  #   affinity:
  #     nodeAffinity:
  #       requiredDuringSchedulingIgnoredDuringExecution:
  #         nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: kubernetes.io/arch
  #             operator: In
  #             values:
  #             - amd64

# Disable all observability components
opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false

components:
  # Configure Browser Telemetry
  frontend:
    envOverrides:
      - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: https://otel-collector.${CLUSTER_DOMAIN}/otlp-http/v1/traces
