---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app.kubernetes.io/name: cart-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
  type: ClusterIP
