{
 "title": "Linkerd DaemonSet",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(process_start_time_seconds{daemonset!=\"\"}, namespace)"
   },
   {
    "name": "daemonset",
    "label": "DaemonSet",
    "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, daemonset)"
   },
   {
    "name": "inbound",
    "query": "label_values(request_total{dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\"}, daemonset)"
   },
   {
    "name": "outbound",
    "query": "label_values(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\"}, dst_daemonset)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">ds/$daemonset</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s])) / sum(irate(response_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "INBOUND DAEMONSETS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{dst_namespace=\"$namespace\", daemonset!=\"\", dst_daemonset!=\"\", dst_daemonset=\"$daemonset\", direction=\"outbound\"}) by (namespace, daemonset))"
    }
   ]
  },
  {
   "title": "OUTBOUND DAEMONSETS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\"}) by (namespace, dst_daemonset))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s])) by (daemonset) / sum(irate(response_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s])) by (daemonset)",
     "legendFormat": "ds/{{daemonset}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\", tls=\"true\"}[30s])) by (daemonset)",
     "legendFormat": "🔒ds/{{daemonset}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\", tls!=\"true\"}[30s])) by (daemonset)",
     "legendFormat": "ds/{{daemonset}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s])) by (le, daemonset))",
     "legendFormat": "p50 ds/{{daemonset}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s])) by (le, daemonset))",
     "legendFormat": "p95 ds/{{daemonset}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}[30s])) by (le, daemonset))",
     "legendFormat": "p99 ds/{{daemonset}}"
    }
   ]
  },
  {
   "title": "Inbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND DAEMONSETS</span>\n</div>"
  },
  {
   "title": "ds/$inbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "inbound",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22.2 },
     "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">ds/$inbound</span>\n</div>"
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24.2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", daemonset!=\"\", daemonset=\"$inbound\", dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (daemonset, pod) / sum(irate(response_total{daemonset!=\"\", daemonset=\"$inbound\", dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (daemonset, pod)",
       "legendFormat": "po/{{pod}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24.2 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{daemonset!=\"\", daemonset=\"$inbound\", dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\", direction=\"outbound\", tls=\"true\"}[30s])) by (daemonset, pod)",
       "legendFormat": "🔒po/{{pod}}"
      },
      {
       "expr": "sum(irate(request_total{daemonset!=\"\", daemonset=\"$inbound\", dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\", direction=\"outbound\", tls!=\"true\"}[30s])) by (daemonset, pod)",
       "legendFormat": "po/{{pod}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24.2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{daemonset!=\"\", daemonset=\"$inbound\", dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (le, daemonset))",
       "legendFormat": "P50 ds/{{daemonset}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{daemonset!=\"\", daemonset=\"$inbound\", dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (le, daemonset))",
       "legendFormat": "P95 ds/{{daemonset}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{daemonset!=\"\", daemonset=\"$inbound\", dst_namespace=\"$namespace\", dst_daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (le, daemonset))",
       "legendFormat": "P99 ds/{{daemonset}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (dst_daemonset) / sum(irate(response_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (dst_daemonset)",
     "legendFormat": "ds/{{dst_daemonset}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_daemonset)",
     "legendFormat": "🔒ds/{{dst_daemonset}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_daemonset)",
     "legendFormat": "ds/{{dst_daemonset}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\"}[30s])) by (le, dst_daemonset))",
     "legendFormat": "P95 ds/{{dst_daemonset}}"
    }
   ]
  },
  {
   "title": "Outbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", direction=\"outbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND DAEMONSETS</span>\n</div>"
  },
  {
   "title": "ds/$outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "outbound",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
     "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">ds/$outbound</span>\n</div>"
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", daemonset=\"$daemonset\", dst_daemonset=\"$outbound\", direction=\"outbound\"}[30s])) by (dst_daemonset) / sum(irate(response_total{namespace=\"$namespace\", daemonset=\"$daemonset\", dst_daemonset=\"$outbound\", direction=\"outbound\"}[30s])) by (dst_daemonset)",
       "legendFormat": "ds/{{dst_daemonset}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", dst_daemonset=\"$outbound\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_daemonset)",
       "legendFormat": "🔒ds/{{dst_daemonset}}"
      },
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", daemonset=\"$daemonset\", dst_daemonset=\"$outbound\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_daemonset)",
       "legendFormat": "ds/{{dst_daemonset}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", dst_daemonset=\"$outbound\", direction=\"outbound\"}[30s])) by (le, dst_daemonset))",
       "legendFormat": "P50 ds/{{dst_daemonset}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", dst_daemonset=\"$outbound\", direction=\"outbound\"}[30s])) by (le, dst_daemonset))",
       "legendFormat": "P95 ds/{{dst_daemonset}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", daemonset=\"$daemonset\", dst_daemonset=\"$outbound\", direction=\"outbound\"}[30s])) by (le, dst_daemonset))",
       "legendFormat": "P99 ds/{{dst_daemonset}}"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<div style=\"display:none\">\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/grafana/\"\n    )\n  )+'/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var versionElem = document.getElementById('version');\n\n  var channel;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    versionElem.innerHTML += 'Running Linkerd ' + parts[1] + ' (' + parts[0] + ')' + '.<br>';\n  } else {\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!channel || !json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>\n</div>"
  }
 ]
}