# grafana helm values (base)
# Use an existing secret for the admin user.
adminUser: ""
adminPassword: ""
admin:
  existingSecret: grafana
  userKey: admin-user
  passwordKey: admin-password

# Install required plugins
plugins:
  - grafana-piechart-panel
# Relabel job name of Grafana's metrics
serviceMonitor:
  enabled: true

# Data sources
datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - { name: Alertmanager, orgId: 1 }
      - { name: Loki, orgId: 1 }
      - { name: Prometheus, orgId: 1 }
      - { name: Tempo, orgId: 1 }
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.kube-prom-stack.svc.cluster.local:9090
      isDefault: true
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      access: proxy
      url: http://kube-prometheus-stack-alertmanager.kube-prom-stack.svc.cluster.local:9093
      jsonData:
        implementation: prometheus
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki-read-headless.loki.svc.cluster.local:3100
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: trace_id
            matcherType: label
            name: TraceID
            url: "$$$${__value.raw}"
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo-query-frontend.tempo.svc.cluster.local:3200
      basicAuth: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: 'loki'
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
          # tags: ['job', 'instance', 'pod', 'namespace']
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: '{$$$${__tags}} | trace_id="$$$${__span.traceId}"'
        tracesToMetrics:
          datasourceUid: 'prometheus'
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
          tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
          queries:
            - name: 'Sample query'
              query: 'sum(rate({"traces.span.metrics.duration_milliseconds_bucket",$$$$__tags}[5m]))'
        serviceMap:
          datasourceUid: 'prometheus'
        nodeGraph:
          enabled: true
        search:
          hide: false
        traceQuery:
          timeShiftEnabled: true
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
        spanBar:
          type: 'Tag'
          tag: 'http.path'
        streamingEnabled:
          search: true
##
## Provisioning sidecars
##
sidecar:
  dashboards:
    # Enable dashboard sidecar
    enabled: true
    # Enable discovery in all namespaces
    searchNamespace: ALL
    # Search for ConfigMaps containing `grafana_dashboard` label
    label: grafana_dashboard
    # Annotation containing the folder where sidecar will place the dashboard.
    folderAnnotation: grafana_folder
    provider:
      # disableDelete to activate a import-only behaviour
      disableDelete: true
      # allow Grafana to replicate dashboard structure from filesystem
      foldersFromFilesStructure: true
  datasources:
    # Enable datasource sidecar
    enabled: true
    # Enable discovery in all namespaces
    searchNamespace: ALL
    # Search for ConfigMaps containing `grafana_datasource` label
    label: grafana_datasource
    labelValue: "1"