apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-elasticsearch-exporter-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: otel-elasticsearch-exporter-secret
  data:
  # Using fluentd user and password from now.
  - secretKey: es-username
    remoteRef:
      key: elastic/otel
      property: username
  - secretKey: es-password
    remoteRef:
      key: elastic/otel
      property: password     
