---
# flux-instance helm values (dev overlay)
instance:
  sync:
    kind: GitRepository
    # Changeme!
    url: https://github.com/olipinski/rdx-cluster
    ref: refs/heads/main
    path: kubernetes/cluster/dev
    interval: 1h
