# ExternalSecret — product-service (e-commerce namespace)
# Provisions: product-service-mongodb-secret (MONGODB_URI assembled from /mongodb/products password)
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: product-service-mongodb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: product-service-mongodb-secret
    creationPolicy: Owner
    template:
      data:
        MONGODB_URI: "mongodb://products_owner:{{ .password }}@mongodb-0.mongodb-svc.databases.svc.cluster.local:27017/products?authSource=admin&replicaSet=mongodb"
  data:
    - secretKey: password
      remoteRef:
        key: /e-commerce/databases/mongodb/products
        property: password
