---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app.kubernetes.io/name: product-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
