apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources: []

patches:
- target:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: bookinfo
  path: bookinfo-patch.yaml
