---
basic_setup_common_packages:
  - curl
  - bridge-utils
  # Longhorn requirements
  - open-iscsi
  - nfs-common
  - cryptsetup
  - dmsetup

basic_setup_radxa_packages:
  - fake-hwclock

basic_setup_raspberrypi_packages:
  - fake-hwclock
