---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    tag: 83.7.0
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prom-stack
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: prometheus-operator-crds
    namespace: kube-system
  - name: longhorn
    namespace: longhorn-system
  valuesFrom:
  - kind: ConfigMap
    name: kube-prometheus-stack-helm-values
    valuesKey: base-values.yaml