---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce

configMapGenerator:
  - name: e-commerce-apm-dashboard
    files:
      - apm-dashboard.json

resources:
  - grafana-dashboard.yaml
