---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: e-commerce-keycloak
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-app
    - name: external-secrets-config
  path: ./kubernetes/apps/e-commerce/config/keycloak/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: e-commerce-kafka
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: kafka
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-config
    - name: kafka-cluster-app
  path: ./kubernetes/apps/e-commerce/config/kafka/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: e-commerce-common
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: e-commerce
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-config
    - name: kafka-cluster-app
  path: ./kubernetes/apps/e-commerce/config/common/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: e-commerce-databases
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: databases
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloudnative-pg-app
    - name: mongodb-community-operator-app
    - name: valkey-operator-app
    - name: external-secrets-config
  path: ./kubernetes/apps/e-commerce/config/databases/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: e-commerce-app
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: e-commerce
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: e-commerce-common
    - name: e-commerce-keycloak
    - name: e-commerce-kafka
    - name: e-commerce-databases
    - name: envoy-gateway-config
    - name: opentelemetry-collector-app
  path: ./kubernetes/apps/e-commerce/app/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
