# longhorn helm values (backup)

# defaultSettings:
#   # Backup S3 configuration
#   backupTarget: "s3://k3s-longhorn@eu-west-1/"
#   backupTargetCredentialSecret: longhorn-s3-secret

# Longhorn 1.12+ backup store configuration
defaultBackupStore:
  backupTarget: "s3://k3s-longhorn@eu-west-1/"
  backupTargetCredentialSecret: "longhorn-s3-secret"
  pollInterval: "300"
