# ExternalSecret — user-service (e-commerce namespace)
# Provisions: user-service-db-secret (username + password, reuses /postgres/users-db)
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: user-service-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /e-commerce/databases/postgresql/users-db
