---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app.kubernetes.io/name: user-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
  type: ClusterIP
