apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: grafana-folder
spec:
  title: Grafana
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: kubernetes-folder
spec:
  title: Kubernetes
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: infrastructure-folder
spec:
  title: Infrastructure
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: istio-folder
spec:
  title: Istio
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: envoy-gateway-folder
spec:
  title: Envoy-Gateway
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: minio-folder
spec:
  title: Minio
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: keycloak-folder
spec:
  title: Keycloak
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: flux-folder
spec:
  title: Flux
  instanceSelector:
    matchLabels:
      dashboards: grafana