apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana
  data:
  - secretKey: admin-user
    remoteRef:
      key: grafana/admin
      property: username
  - secretKey: admin-password
    remoteRef:
      key: grafana/admin
      property: password
  - secretKey: elasticsearch-username
    remoteRef:
      key: elastic/grafana
      property: username
  - secretKey: elasticsearch-password
    remoteRef:
      key: elastic/grafana
      property: password
