apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prom-elasticsearch-exporter-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: elasticsearch-exporter-secrets
  data:
  - secretKey: username
    remoteRef:
      key: elastic/prometheus
      property: username
  - secretKey: password
    remoteRef:
      key: elastic/prometheus
      property: password
