---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-elasticsearch-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-elasticsearch-exporter
  ref:
    tag: 7.2.1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-elasticsearch-exporter
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: prometheus-elasticsearch-exporter
  releaseName: prometheus-elasticsearch-exporter
  targetNamespace: elastic
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-elasticsearch-exporter-helm-values
    valuesKey: base-values.yaml