---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-alertmanager-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-alertmanager-externalsecret
  data:
  - secretKey: client-id
    remoteRef:
      key: alertmanager/oauth2
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: alertmanager/oauth2
      property: client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-prometheus-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-prometheus-externalsecret
  data:
  - secretKey: client-id
    remoteRef:
      key: prometheus/oauth2
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: prometheus/oauth2
      property: client-secret