---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-operator
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    tag: 5.22.2
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: grafana-operator
  releaseName: grafana-operator
  targetNamespace: grafana
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: grafana-operator-helm-values
    valuesKey: base-values.yaml
