---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-mailserver-tls
  namespace: docker-mailserver
spec:
  # Secret names are always required.
  secretName: docker-mailserver-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: mail.${CLUSTER_DOMAIN}
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - mail.${CLUSTER_DOMAIN}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
