---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-mailserver-app-externalsecret
  namespace: docker-mailserver
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: docker-mailserver-app-secret
  data:
    - secretKey: DMS_DKIM_KEYS_PRIVATE
      remoteRef:
        key: dms-dkim/keys
        property: private
    - secretKey: DMS_DKIM_KEYS_PUBLIC
      remoteRef:
        key: dms-dkim/keys
        property: public
    - secretKey: DMS_DKIM_KEYS_DNS
      remoteRef:
        key: dms-dkim/keys
        property: dns
