apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - peer-authentication.yaml
  - webhook-metrics-permissive.yaml
  - metrics-permissive.yaml

patches:
  - path: namespace-labels.yaml
    target:
      kind: Namespace
      name: kafka
