---
- name: Get CLI configured namespace # noqa: no-changed-when
  ansible.builtin.command:
    cmd: velero client config get namespace
  register: velero_cli_get_velero_namespace
  ignore_errors: true

- name: Configure velero CLI namespace # noqa: no-changed-when
  ansible.builtin.command:
    cmd: "velero client config set namespace={{ velero_cli_velero_namespace }}"
  when:
    - velero_cli_get_velero_namespace.rc==0
    - '"namespace: <NOT SET>" in velero_cli_get_velero_namespace.stdout or "namespace: " + velero_cli_velero_namespace not
      in velero_cli_get_velero_namespace.stdout'

- name: Get CLI configured coloured # noqa: no-changed-when
  ansible.builtin.command:
    cmd: velero client config get colored
  register: velero_cli_get_velero_colored
  ignore_errors: true

- name: Configure velero CLI coloured output # noqa: no-changed-when
  ansible.builtin.command:
    cmd: velero client config set colored=true
  when:
    - velero_cli_get_velero_colored.rc==0
    - '"colored: <NOT SET>" in velero_cli_get_velero_colored.stdout or "colored: true" not in velero_cli_get_velero_colored.stdout'
