# ExternalSecrets — order-service (e-commerce namespace)
# Provisions: order-service-db-secret, order-service-oauth-secret, order-service-kafka-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: order-service-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /e-commerce/databases/postgresql/orders-db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-oauth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: order-service-oauth-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /e-commerce/keycloak/clients/order-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-kafka-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: order-service-kafka-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /kafka/order-service
