apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-bearer-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: s3-monitor-token
    template:
      engineVersion: v2
      data:
        token: "{{ .token | toString }}"
  data:
  - secretKey: token
    remoteRef:
      key: s3/prometheus
      property: bearer-token
