---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: vault
spec:
  jobName: vault
  authorization:
    credentials_file: /vault/secrets/token
  metricsPath: /v1/sys/metrics
  params:
    format: ['prometheus']
  scheme: HTTPS
  staticConfigs:
  - targets:
    - vault.${CLUSTER_DOMAIN}:8200
