# ExternalSecrets — reviews-service (e-commerce namespace)
# Provisions: reviews-service-mongodb-secret, reviews-service-oauth-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reviews-service-mongodb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: reviews-service-mongodb-secret
    creationPolicy: Owner
    template:
      data:
        MONGODB_URI: "mongodb://reviews_owner:{{ .password }}@mongodb-0.mongodb-svc.databases.svc.cluster.local:27017/reviews?authSource=admin&replicaSet=mongodb"
  data:
    - secretKey: password
      remoteRef:
        key: /e-commerce/databases/mongodb/reviews
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reviews-service-oauth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: reviews-service-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: REVIEWS_SERVICE_CLIENT_SECRET
      remoteRef:
        key: /e-commerce/keycloak/clients/reviews-service
        property: CLIENT_SECRET
