---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app.kubernetes.io/name: reviews-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
