---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluent
spec:
  interval: 1h
  url: oci://ghcr.io/fluent/helm-charts/fluentd
  ref:
    tag: 0.5.3
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: fluent
  releaseName: fluentd
  targetNamespace: fluent
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: fluentd-helm-values
    valuesKey: base-values.yaml