apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: valkey
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              valkey.io/cluster: valkey
          topologyKey: kubernetes.io/hostname
