---
# Minio prometheus bearer token was created and stored in filesystem
- name: Load prometheus bearer token from file in vault node
  ansible.builtin.command: "jq -r '.bearerToken' /etc/minio/prometheus_bearer.json"
  register: root_token
  become: true
  changed_when: false
  when: minio_prom_bearer_token is not defined
  delegate_to: node1

- name: Get bearer token
  ansible.builtin.set_fact:
    minio_prom_bearer_token: "{{ root_token.stdout }}"

- name: Create/update minio/prometheus credentials in Vault
  community.hashi_vault.vault_write:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    validate_certs: "{{ not (enable_letsencrypt | default(false)) }}"
    ca_cert: "{{ vault_cacert | default(omit) }}"
    path: "secret/data/minio/prometheus"
    data:
      data:
        bearer-token: "{{ minio_prom_bearer_token }}"
  no_log: true
