---
# Execute tasks to install cli and utils
- name: Install flux-cd cli
  ansible.builtin.include_tasks: install_fluxcd_cli.yml

- name: Install longhorn cli
  ansible.builtin.include_tasks: install_longhorn_cli.yml

- name: Install longhorn utilities
  ansible.builtin.include_tasks: install_longhorn_util.yml

- name: Install velero cli
  ansible.builtin.include_tasks: install_velero_cli.yml

- name: Configure velero cli
  ansible.builtin.include_tasks: configure_velero_cli.yml
