apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hubble-oauth2-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hubble-oauth2-externalsecret
  data:
  - secretKey: client-id
    remoteRef:
      key: hubble/oauth2
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: hubble/oauth2
      property: client-secret