---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: strimzi
spec:
  interval: 1h
  url: oci://quay.io/strimzi-helm/strimzi-kafka-operator
  ref:
    tag: 1.0.0
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: strimzi
  releaseName: strimzi-kafka-operator
  targetNamespace: kafka
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: strimzi-kafka-operator-helm-values
    valuesKey: base-values.yaml