---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
spec:
  url: https://kubernetes-sigs.github.io/external-dns
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  releaseName: external-dns
  targetNamespace: external-dns
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: external-dns-helm-values
    valuesKey: base-values.yaml