---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  EXTERNAL_DNS_SERVER: 10.20.0.1
  NGINX_LOAD_BALANCER_IP: 10.128.0.100
  FLUENTD_LOAD_BALANCER_IP: 10.128.0.101
  ISTIO_GATEWAY_LOAD_BALANCER_IP: 10.128.0.102

  PI_ADMIN_FIRSTNAME: Da
  PI_ADMIN_LASTNAME: Shi
