# ExternalSecrets — MongoDB (databases namespace)
# Backed by Vault via ClusterSecretStore 'vault-backend'.
# Secrets created:
#   mongodb-products-secret      ← product-service MongoDB user
#   mongodb-reviews-secret       ← reviews-service MongoDB user
#   mongodb-notifications-secret ← notification-service MongoDB user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-products-externalsecret
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-products-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /e-commerce/databases/mongodb/products
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-reviews-externalsecret
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-reviews-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /e-commerce/databases/mongodb/reviews
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-notifications-externalsecret
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-notifications-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /e-commerce/databases/mongodb/notifications