# ExternalSecret — notification-service (e-commerce namespace)
# Provisions: notification-service-kafka-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service-kafka-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: notification-service-kafka-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /kafka/notification-service
