---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-mailserver-config-externalsecret
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: docker-mailserver-config-secret
  data:
    - secretKey: DMS_ADMIN_USER
      remoteRef:
        key: dms/admin
        property: user
    - secretKey: DMS_ADMIN_HASHED_PASSWORD
      remoteRef:
        key: dms/admin
        property: hashed_password
