apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-istiod
  labels:
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      app: istiod
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 30s
