# fluent-bit helm values (monitoring)

# Enable Prometheus operator service monitor
serviceMonitor:
  enabled: true

# Enable Grafana dashboard
dashboards:
  enabled: true
  annotations:
    grafana_folder: "Logging"