# fluent-bit helm values (monitoring)

# Enable Prometheus operator service monitor
serviceMonitor:
  enabled: true

# Enable Grafana dashboard
dashboards:
  enabled: true
  labelKey: app.kubernetes.io/managed-by
  labelValue: grafana-operator
  annotations:
    grafana_folder: "Logging"