apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - certificate.yaml
  - envoy-proxy.yaml
  - gateway-class.yaml
  - gateway.yaml
  - client-traffic-policy.yaml
  - backend-traffic-policy.yaml
  - http-redirect-route.yaml