---
# k3s server connection token
k3s_agent_k3s_token: s1cret0

# Setting K3s version
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_agent_k3s_version: v1.33.2+k3s1

# k3s config file
k3s_agent_k3s_config_file: "{{ k3s_agent_k3s_config_dir }}/config.yaml"

# k3s registries file
k3s_agent_k3s_registries_file: "{{ k3s_agent_k3s_config_dir }}/registries.yaml"

# k3s kubelet config content
k3s_agent_k3s_kubelet_config: ""

# k3s agent config
k3s_agent_config: ""
