# kiali-operator helm values (base)

cr:
  create: true
  namespace: kiali
  spec:
    istio_namespace: "istio-system"
    server:
      web_fqdn: "kiali.${CLUSTER_DOMAIN}"
      web_port: "443"
      web_schema: "https"
      web_root: "/"
    auth:
      # strategy: "anonymous"
      strategy: openid
      openid:
        client_id: "kiali"
        disable_rbac: true
        issuer_uri: "https://iam.${CLUSTER_DOMAIN}/realms/picluster"
    external_services:
      prometheus:
        # Prometheus service
        url: "http://kube-prometheus-stack-prometheus.kube-prom-stack:9090/prometheus/"
      grafana:
        enabled: true
        # Grafana service name is "grafana" and is in the "grafana" namespace.
        internal_url: 'http://grafana.grafana.svc.cluster.local/grafana/'
        # Public facing URL of Grafana
        external_url: 'https://grafana.${CLUSTER_DOMAIN}'
        auth:
          # Use same OAuth2.0 token used for accesing Kiali
          type: bearer
          use_kiali_token: true
      tracing:
        # Enabled by default. Kiali will anyway fallback to disabled if
        # Tempo is unreachable.
        enabled: true
        # Tempo service name is "query-frontend" and is in the "tempo" namespace.
        internal_url: "http://tempo-query-frontend.tempo.svc.cluster.local:3100/"
        provider: "tempo"
        tempo_config:
          org_id: "1"
          datasource_uid: "a8d2ef1c-d31c-4de5-a90b-e7bc5252cd00"
        # Use grpc to speed up the download of metrics
        use_grpc: true
        grpc_port: 9095
    deployment:
      # Enabling debug logs
      logger:
        log_level: debug