---
- name: Generate vault variables file
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: cloudflare_token_ddns
      prompt: Enter the Cloudflare token for DDNS
      private: true
    - name: cloudflare_token_certmanager
      prompt: Enter the Cloudflare token for CertManager
      private: true
    - name: wifi_password
      prompt: Enter WiFI Password
      private: true
    - name: sec_org
      prompt: Enter organisation name
      private: true
    - name: sec_dns_domain
      prompt: Enter DNS domain
      private: true

  pre_tasks:
    - name: Get GitHub PAT credentials
      when: git_private_repo
      block:
        - name: Ask for GitHub PAT credentials
          ansible.builtin.pause:
            prompt: "Enter Github PAT: "
            echo: false
          register: prompt
        - name: Set GitHub pat password variable
          ansible.builtin.set_fact:
            github_pat: "{{ prompt.user_input }}"
          no_log: true
    - name: Get Telegram credentials
      when: smartmontools_notification_format == "telegram"
      block:
        - name: Ask for Telegram chat ID
          ansible.builtin.pause:
            prompt: "Enter the Telegram chat ID: "
            echo: false
          register: chat_id
        - name: Ask for Telegram bot API key
          ansible.builtin.pause:
            prompt: "Enter the Telegram bot API key: "
            echo: false
          register: bot_key
        - name: Set Telegram chat ID
          ansible.builtin.set_fact:
            telegram_chat_id: "{{ chat_id.user_input }}"
          no_log: true
        - name: Set Telegram boot API key
          ansible.builtin.set_fact:
            telegram_api_key: "{{ bot_key.user_input }}"
          no_log: true
  tasks:
    - name: Create random passwords
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      with_items:
        - k3s_token
        - minio_root_password
        - minio_restic_password
        - minio_longhorn_password
        - minio_velero_password
        - minio_loki_password
        - minio_tempo_password
        - minio_barman_password
        - traefik_basic_auth_password
        - fluentd_shared_key
        - grafana_admin_password
        - elasticsearch_admin_password
        - elasticsearch_fluentd_password
        - elasticsearch_prometheus_password
        - keycloak_admin_password
        - keycloak_pi_password
        - keycloak_postgresql_password
        - oauth2_proxy_client_secret
        - oauth2_proxy_cookie
        - oauth2_proxy_redis_password
        - grafana_client_secret
        - kiali_client_secret
        - postgresql_admin_password
        - kafka_admin_password
        - kafka_kafdrop_password
        - kafka_schema_registry_password
        - schema_registry_basic_auth_password
        - docker_mailserver_password

    - name: Generate WireGuard private key # noqa: no-changed-when
      ansible.builtin.command: wg genkey
      register: wg_private_key
      no_log: true

    - name: Generate DKIM private key in memory
      community.crypto.openssl_privatekey_pipe:
        size: 2048
        type: RSA
      register: dkim_private_key
      no_log: true

    - name: Extract DKIM public key
      community.crypto.openssl_publickey:
        privatekey_content: "{{ dkim_private_key.privatekey }}"
        return_content: true
        path: /tmp/public_key_temp
      register: dkim_public_key
      no_log: true

    - name: Set DKIM private key fact
      ansible.builtin.set_fact:
        dkim_private_key: "{{ dkim_private_key.privatekey }}"

    - name: Set DKIM public key fact
      ansible.builtin.set_fact:
        dkim_public_key: "{{ dkim_public_key.publickey }}"

    - name: Clean up temporary file
      ansible.builtin.file:
        path: /tmp/public_key_temp
        state: absent

    - name: Convert public key to DNS format
      ansible.builtin.set_fact:
        dkim_public_key_dns: >-
          {{ dkim_public_key
             | regex_replace('-----BEGIN PUBLIC KEY-----', '')
             | regex_replace('-----END PUBLIC KEY-----', '')
             | regex_replace('\n', '')
          }}
      no_log: true

    - name: Hash mailserver password
      ansible.builtin.set_fact:
        docker_mailserver_password_hashed: >-
          {{ docker_mailserver_password | ansible.builtin.password_hash('sha512') }}
      no_log: true

    - name: Generate vault file
      ansible.builtin.template:
        src: vars/vault.yaml.j2
        dest: vars/vault_unenc.yaml
        mode: "755"

    - name: Encrypt file
      ansible.builtin.command:
        argv:
          - ansible-vault encrypt
          - --vault-password-file=./.vault/vault-pass.sh
          - vars/vault_unenc.yaml
          - -output
          - vars/vault.yaml
        creates: vars/vault.yaml # Do not create a new encrypted vault, if one already exists

    - name: Clean up temporary vault file
      ansible.builtin.file:
        path: vars/vault_unenc.yaml
        state: absent
