---
- name: Install helm and kubectl
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    install_kubectl: true
    install_helm: true
    k8s_platform: linux
    k8s_arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    kubectl_version: 1.35.1
    # SHA512 checksum of the binary (see https://dl.k8s.io/release/v1.35.1/bin/linux/amd64/kubectl.sha512)
    kubectl_checksum_binary: "{{ 'sha512:472a77ca5eb6d53ad1f23bad79a56973cc7a2701cfa93fc28b4411bacfbd2311fe498dfcf81e1e6296d77b344c765f22426a3cb8b53b1639f51c2a1dfa0a898e'
      if ansible_facts.architecture == 'aarch64' else 'sha512:0d23d8c5022cdf07aa04df8538cda7bf030bfdc445e77ce009f83ffbae73e19462621a226bd03358ee44aa6f6acae1b558cdf2ae42685b4c5f8565aefd73df73'
      }}"
    # renovate: datasource=github-releases depName=helm/helm
    helm_version: v4.1.4
  roles:
    - role: ricsanfre.k8s_cli

- name: Install other utilities
  hosts: localhost
  gather_facts: true
  become: true
  pre_tasks:
    - name: Include rdxcluster variables
      ansible.builtin.include_vars: vars/rdxcluster.yaml
      tags:
        - always
  roles:
    - role: fluxcd_cli
    - role: longhorn_cli
    - role: velero_cli
      vars:
        velero_cli_velero_arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - role: istio_cli
