---
- name: Stop K3s servers
  hosts: k3s_server
  become: true
  gather_facts: false
  tasks:
    - name: Stop K3S Service
      ansible.builtin.service:
        name: k3s
        state: stopped

- name: Stop K3s agents
  hosts: k3s_agent
  become: true
  gather_facts: false
  tasks:
    - name: Stop K3S Service
      ansible.builtin.service:
        name: k3s-agent
        state: stopped

- name: Stop all K3s server containers
  hosts: k3s_server
  become: true
  gather_facts: false
  tasks:
    - name: Stop k3s containers and free network resources # noqa: no-changed-when
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh

- name: Stop all K3s agent containers
  hosts: k3s_agent
  become: true
  gather_facts: false
  tasks:
    - name: Stop k3s containers and free network resources # noqa: no-changed-when
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh
