---

# - name: Configure Pi Cluster Gateway (Ubuntu)
#   hosts: gateway
#   gather_facts: true
#   tags: [gateway]
#   become: true
#   roles:

#     # OS basic setup tasks
#     - role: basic_setup
#       tags: [os]

#     # Security Hardening
#     - role: ricsanfre.security
#       tags: [security]

#     # DNS Resolver Forwarder configuration
#     # DHCP server configuration
#     - role: ricsanfre.dnsmasq
#       tags: [dns]

#     # Update DNS server to point to DNSmasq
#     - role: dns
#       tags: [dns]

#     # Firewall (nftables) configuration
#     - role: ricsanfre.firewall
#       tags: [firewall]

#     # NTP Server configuration
#     - role: ricsanfre.ntp
#       tags: [ntp]

- name: Configure External Node
  hosts: node1
  gather_facts: true
  tags: [external]
  become: true
  roles:
    # OS basic setup tasks
    - role: basic_setup
      tags: [os]

    # Security Hardening
    - role: ricsanfre.security
      tags: [security]

    # NTP Client configuration
    - role: ricsanfre.ntp
      tags: [ntp]

- name: Configure Pi Cluster Nodes
  hosts: k3s_cluster
  gather_facts: true
  tags: [node]
  become: true
  roles:
    # OS basic setup tasks
    - role: basic_setup
      tags: [os]

    # Security Hardening
    - role: ricsanfre.security
      tags: [security]

    # NTP Client configuration
    - role: ricsanfre.ntp
      tags: [ntp]

  tasks:
    # Local Storage configuration
    - name: Dedicated Disks
      block:
        # iSCSI client (initiator) configuration
        # iSCSI initiator needs to be configured for Longhorn
        - name: Configure iSCSI Initiator
          include_role:
            name: ricsanfre.iscsi_initiator
          vars:
            open_iscsi_initiator_name: "iqn.2021-07.com.ricsanfre.homelab:{{ ansible_facts['nodename'] }}"
            open_iscsi_automatic_startup: true
      tags: [storage]
