apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-externalsecret
  namespace: loki
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: loki-s3-secret
    template:
      engineVersion: v2
      data:
        S3_ACCESS_KEY_ID: "{{ .user | toString }}"
        S3_SECRET_ACCESS_KEY: "{{ .key | toString }}"
  data:
  - secretKey: user
    remoteRef:
      key: s3/loki
      property: username
  - secretKey: key
    remoteRef:
      key: s3/loki
      property: key
