source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!

# gem "jekyll", "~> 4.2.1"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-toc"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]

# Warning:  github-pages can't satisfy your Gemfile's dependencies.
# To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
# https://github.com/TWiStErRob/twisterrob.github.io/commit/f0040c33b959c19e7bc834043b01d48715a91b38
# This was added as a workaround for https://github.com/actions/jekyll-build-pages/issues/104
# and https://github.com/github/pages-gem/issues/887
install_if -> { ENV["GITHUB_ACTIONS"] != "true" } do
  gem "webrick", "~> 1.8"
  gem 'faraday-retry', '~> 2.3.0'
end
