# ExternalSecret — MongoDB prometheus exporter user password
# Backed by Vault via ClusterSecretStore 'vault-backend'.
# Creates secret: mongodb-prometheus-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-prometheus-externalsecret
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-prometheus-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /e-commerce/databases/mongodb/prometheus
