---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v6

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install test dependencies.
        run: pip3 install yamllint hvac

      - name: Check spelling.
        uses: codespell-project/actions-codespell@v2
        with:
          skip: docs,design
          builtin: clear,rare,informal

      - name: Ansible-lint the Ansible YAMLs.
        uses: ansible/ansible-lint@v26.4.0

      - name: Lint all the Kubernetes YAMLs.
        run: yamllint kubernetes/

      - name: Kube-lint the Kubernetes YAMLs.
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ./kubernetes
          config: .kube-linter.yaml
